################################################################################
# libukvirtgpu_drm — Mesa/Linux virtgpu UAPI shim (flat, mirrors Mesa src/virtio/vdrm/)
################################################################################
$(eval $(call addlib,libukvirtgpu_drm))

LIBUKVIRTGPU_DRM_SRCS-y += $(LIBUKVIRTGPU_DRM_BASE)/vdrm_virtgpu.c
LIBUKVIRTGPU_DRM_SRCS-$(CONFIG_LIBUKVIRTGPU_DRM_FDIO) += $(LIBUKVIRTGPU_DRM_BASE)/vdrm.c

LIBUKVIRTGPU_DRM_CINCLUDES-y += -I$(LIBUKVIRTGPU_DRM_BASE)/include
LIBUKVIRTGPU_DRM_CINCLUDES-y += -I$(LIBUKVIRTIO_GPU_BASE)/include
