= System Overview <sec:system-overview>

@fig:vogue-arch shows the VOGUE library stack. The system is organized as Unikraft micro-libraries, each with an explicit dependency declaration and a build file that compiles only what is needed. The design rule is conservative: VOGUE reuses Unikraft's existing PCI, virtio, allocator, mmap/POSIX, and synchronization infrastructure and only adds the graphics-specific protocol and compatibility layers.

#include "../figures/vogue-arch.typ"

== Layer Responsibilities

Since the design optimizes for a narrow data plane and explicit compatibility contracts, each layer has a well-defined responsibility:

Device-backing memory is allocated with Unikraft's allocator (`uk_posix_memalign`) and described with the upstream scatter-gather library (`uksglist`); VOGUE introduces no independent memory manager or first-party DMA library. This is the only place VOGUE touches guest-physical memory layout for virtio backing, and it reuses Unikraft primitives directly.

*libukvirtio_gpu* implements the VirtIO-GPU protocol on top of Unikraft's existing virtio/PCI stack: command encoding and submission, response parsing, fence creation and polling, 2D resource management, capset discovery, context management, 3D submit, resource blobs, UUID assignment, and map/unmap helpers. The 2D path is exercised by native display tests. The 3D/blob path is implemented as a real control-queue surface and checked by ABI/static/readiness gates. On the evaluation host the current generated matrix records QEMU/Venus execution, the Mesa-compatible Venus ring-buffer protocol, KMSCube virgl frame proof, and upstream llama.cpp Vulkan runtime as PASS with same-run artifacts.

*libukswrender* is a CPU software rasterizer that renders rotating-cube geometry into a BGRA framebuffer. It takes a rotation angle and an output pixel buffer; internally it clips triangles, performs perspective-correct interpolation, and writes packed 32-bit pixels. It has no dependency on any graphics API.

*libukegl* provides the EGL/GLES2/GBM/DRM shim. On EGL initialization, it opens a connection to `libukvirtio_gpu` and queries capsets. On EGL window surface creation, it allocates a software framebuffer and a DMA buffer. On EGL buffer swap, it invokes `libukswrender` to produce the current frame's pixels, then copies them to DMA memory and issues a host-transfer followed by a resource-flush command. Unsupported Linux DRM behavior remains an explicit safe stub rather than a hidden partial reimplementation.

== Dependency Collapse and Protocol Seam

The most important architectural difference between Linux and VOGUE is not the
host protocol — both eventually speak VirtIO-GPU and, for Vulkan, the Venus
command transport — but the guest-side dependency structure required to reach
that protocol seam.

In Linux, the guest path typically flows through the DRM/KMS subsystem,
libdrm, GBM/EGL integration, Mesa drivers, and then either VirGL or Venus
guest logic before a command reaches QEMU or virglrenderer @drm-kms @mesa
@qemu-vgpu @venus. In VOGUE, the corresponding path is intentionally thinner:
application port → compatibility shim → `libukvirtio_gpu` or
`libukvirtgpu_drm`/`libukvenus` → VirtIO-GPU/Venus seam. The internal
dependency graph generated by `make depgraph` makes this contrast explicit.
View A shows the collapse of the Linux guest tower into a thin `libuk*` chain;
View B distinguishes build, compile, and runtime edges on the VOGUE Vulkan
path; View C shows the invariant spine where Linux and VOGUE emit the same
protocol commands to the host.

This distinction matters for both systems design and evaluation. Architecturally,
it shows that VOGUE is not attempting to clone the Linux graphics stack inside
Unikraft; it is identifying the minimum guest-side layers needed to reach the
same host-facing contract. Methodologically, it explains why the paper's claims
are phrased around bounded compatibility, explicit non-goals, and protocol-seam
evidence rather than around wholesale Linux feature equivalence.

== Display Pipeline

A single software-rendered frame traverses the following path. The application calls the EGL buffer-swap routine, which triggers `libukswrender` to produce the current frame's pixels at the current rotation angle. The shim copies the resulting pixel data to DMA-backed memory, then issues a `TRANSFER_TO_HOST_2D` command to push the framebuffer into the host-managed resource, followed by a `RESOURCE_FLUSH` command to present it to the virtual display. A fence waits for device completion before the next frame begins. This pipeline is identical whether the application is _kmscube_ or _glmark2_; only the pixel production step differs.

@fig:frame-pipeline shows the six-step per-frame data flow. Steps 3–5 (TRANSFER, FLUSH, fence) repeat every frame at ~4 MB per frame for 1280×800 BGRA output.

#include "../figures/frame-pipeline.typ"

== Accelerated Path Boundary

The accelerated path is intentionally separated from the working software path.
VOGUE has transport-level commands for context creation, attach/detach,
`SUBMIT_3D`, blob allocation, UUID assignment, and map/unmap, plus a
Mesa-compatible Venus encoder and ring protocol. These pieces are necessary for
virgl/Venus acceleration, but the paper never treats them as equivalent to
application success on their own. The stronger claims — QEMU/Venus transport,
pixel-checked virgl rendering, and end-to-end llama.cpp Vulkan runtime — are
promoted only when same-run artifacts exist. This separation is what makes the
current 27/27 PASS matrix credible instead of rhetorical.
