#pragma once
#include <EGL/egl.h>

/* Extension function-pointer typedefs used by kmscube/glmark2 */
typedef EGLDisplay (*PFNEGLGETPLATFORMDISPLAYEXTPROC)(
        EGLenum, void*, const EGLint*);
typedef EGLSurface (*PFNEGLCREATEPLATFORMWINDOWSURFACEEXTPROC)(
        EGLDisplay, EGLConfig, void*, const EGLint*);
typedef EGLSurface (*PFNEGLCREATEPLATFORMPIXMAPSURFACEEXTPROC)(
        EGLDisplay, EGLConfig, void*, const EGLint*);
typedef EGLImageKHR (*PFNEGLCREATEIMAGEKHRPROC)(
        EGLDisplay, EGLContext, EGLenum, void*, const EGLint*);
typedef EGLBoolean  (*PFNEGLDESTROYIMAGEKHRPROC)(EGLDisplay, EGLImageKHR);
typedef EGLSyncKHR  (*PFNEGLCREATESYNCKHRPROC)(EGLDisplay,EGLenum,const EGLint*);
typedef EGLBoolean  (*PFNEGLDESTROYSYNCKHRPROC)(EGLDisplay, EGLSyncKHR);
typedef EGLint      (*PFNEGLCLIENTWAITSYNCKHRPROC)(EGLDisplay,EGLSyncKHR,EGLint,EGLuint64KHR);
typedef EGLint      (*PFNEGLWAITSYNCKHRPROC)(EGLDisplay,EGLSyncKHR,EGLint);
typedef int         (*PFNEGLDUPLICATENATIVEFENCEFDANDROIDPROC)(EGLDisplay,EGLSyncKHR);
#define PFNEGLDUPNATIVEFENCEFDANDROIDPROC PFNEGLDUPLICATENATIVEFENCEFDANDROIDPROC

#define EGL_IMAGE_PRESERVED_KHR       0x30D2
#define EGL_LINUX_DMA_BUF_EXT         0x3270
#define EGL_DMA_BUF_PLANE0_FD_EXT     0x3272
#define EGL_DMA_BUF_PLANE0_OFFSET_EXT 0x3273
#define EGL_DMA_BUF_PLANE0_PITCH_EXT  0x3274
#define EGL_DMA_BUF_PLANE1_FD_EXT     0x3275
#define EGL_DMA_BUF_PLANE1_OFFSET_EXT 0x3276
#define EGL_DMA_BUF_PLANE1_PITCH_EXT  0x3277
#define EGL_DMA_BUF_PLANE2_FD_EXT     0x3278
#define EGL_DMA_BUF_PLANE2_OFFSET_EXT 0x3279
#define EGL_DMA_BUF_PLANE2_PITCH_EXT  0x327A
#define EGL_YUV_COLOR_SPACE_HINT_EXT  0x327B
#define EGL_SAMPLE_RANGE_HINT_EXT     0x327C
#define EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT 0x327D
#define EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT   0x327E
/* plane modifier extensions */
#define EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT 0x3443
#define EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT 0x3444
#define EGL_DMA_BUF_PLANE1_MODIFIER_LO_EXT 0x3445
#define EGL_DMA_BUF_PLANE1_MODIFIER_HI_EXT 0x3446
#define EGL_DMA_BUF_PLANE2_MODIFIER_LO_EXT 0x3447
#define EGL_DMA_BUF_PLANE2_MODIFIER_HI_EXT 0x3448
#define EGL_DMA_BUF_PLANE3_FD_EXT          0x3440
#define EGL_DMA_BUF_PLANE3_OFFSET_EXT      0x3441
#define EGL_DMA_BUF_PLANE3_PITCH_EXT       0x3442
#define EGL_DMA_BUF_PLANE3_MODIFIER_LO_EXT 0x3449
#define EGL_DMA_BUF_PLANE3_MODIFIER_HI_EXT 0x344A
